# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

WORKDIR /app
COPY . .

# Create virtual environment
RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"

# Install Python dependencies
RUN pip install --no-cache-dir --break-system-packages "mcp[cli]>=1.9.4" "crawl4ai>=0.6.3"

CMD ["python", "main.py"]
